# Generated by Django 5.2.4 on 2025-08-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='calculation_mod',
            field=models.CharField(choices=[('DISTANCE', 'Distance'), ('DURATION', 'Duration')], default='DISTANCE', max_length=10),
        ),
        migrations.AddField(
            model_name='run',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='user.etablissement'),
        ),
        migrations.AddField(
            model_name='run',
            name='mode',
            field=models.CharField(choices=[('NO_START', 'no_start'), ('NO_END', 'no_end'), ('CLOSED', 'closed')], default='CLOSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10),
        ),
    ]
