# Generated by Django 5.2.4 on 2025-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_run_calculation_mod_run_etablissement_run_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='capacity',
        ),
        migrations.AddField(
            model_name='run',
            name='vehicules',
            field=models.CharField(choices=[('VOITURES', 'Voitures (5 places)'), ('VANS', 'Vans (9 places)'), ('VOITURES_ET_VANS', 'Voitures et vans')], default='VOITURES', max_length=50),
        ),
    ]
