# Generated by Django 5.2.4 on 2025-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_remove_run_capacity_run_vehicules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='calculation_mod',
            field=models.CharField(choices=[('DISTANCE', 'Distance'), ('DURATION', 'Durée')], default='DISTANCE', max_length=10),
        ),
        migrations.AlterField(
            model_name='run',
            name='mode',
            field=models.CharField(choices=[('NO_START', 'Vers le dépôt'), ('NO_END', 'Depuis le depôt'), ('CLOSED', 'Vers et depuis le dépôt (boucle)')], default='CLOSED', max_length=10),
        ),
    ]
