# Generated by Django 5.2.4 on 2025-08-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='user.etablissement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresse',
            name='num_et_rue',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='prenom',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
