# Generated by Django 5.2.4 on 2025-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groupe_etablissement_alter_adresse_num_et_rue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
