# Generated by Django 5.2.4 on 2025-08-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_adresse_latitude_alter_adresse_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='tuteur',
            field=models.CharField(default='parents', max_length=100),
        ),
    ]
