# Generated by Django 5.2.4 on 2025-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_enfant_tuteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='tuteur',
            field=models.CharField(default='Parents', max_length=100),
        ),
    ]
